### ISSUE TITLE
Tickets

### ISSUE THREAD

**Issue by sean0x42** [sean0x42/riverrats.com.au#21]
Whenever a game is recorded, the admin can set an amount of tickets to award `n`. The top `n` players are then awarded a ticket.

Tickets are displayed publicly on player's profiles, and can be manually cleared by administrators when major events take place.

**Comment by eehan87** [comment]
Can this be added to be done fairly soon, as we have our big game on the 3rd of the 11th and it'll be handy to be able to assign tickets to the previous games, and print this list off for the entry.

Some examples of formatting - we set a custom variable (x amount of tickets at Bellevue on the 1/10/18 and then the top 5 players get 1 ticket added to their counters

Then in the printed list, for example player Grant Relf has 22 tickets. His first ticket would give him 50k starting stack, then every additional ticket would give him 5k extra. So 
1x 50,000 + 21x5,000 = 155,000 chips

Additionally, admin should have a section where we can manually assign tickets to certain players if they win them during games for random things, so the menu box would be 

Type players name: Grant Relf
Amount of tickets: x
Are you adding or subtracting tickets [ add ] [ sub ]
x = variable amount

On this page, there needs to be a history of which administrator adds tickets, in the event of funny business.

**Comment by sean0x42** [comment]
Okay, I'll try and bump it forward a little

**Comment by sean0x42** [comment]
Resolved in 1.2.0
