### ISSUE TITLE
Player ranks in 'Create Game'

### ISSUE THREAD

**Issue by eehan87** [sean0x42/riverrats.com.au#90]
**Is your feature request related to a problem? Please describe.**
Previously, in adding players to a game, there was positional numbers next to their name

1st, 2nd, 3rd etc. This has disappeared, and it was a great feature, can it be re-added please.

**Comment by sean0x42** [comment]
Absolutely, I'll work on this for today's hotfix.

**Comment by sean0x42** [comment]
Resolved in hotfix 1.2.1
