### ISSUE TITLE
Instead of selecting the date of the game, the system automatically generates the games?

### ISSUE THREAD

**Issue by eehan87** [sean0x42/riverrats.com.au#91]
**Is your feature request related to a problem? Please describe.**
Not a problem exactly, but would be convenient

**Describe the solution you'd like**
When you click Create Game, and the menu says Played On, instead of that, can it say "Select Venue" you select Bellevue Hotel Monday, and it brings up ONLY the dates on Mondays that a score hasn't been submitted on? Essentially, this would allow us to know if there are any days that scores have been missed. I keep perfect records, so I have a book that I cross-reference and mark off as I go, but other people aren't as organized.

**Comment by sean0x42** [comment]
I can definitely see the importance of making sure no records are missed, but I'm not sure this is an achievable way to implement it. Does #96 help with this problem at all?

**Comment by eehan87** [comment]
Yes, #96 would definitely fix this on a global level.

**Comment by sean0x42** [comment]
Alright perfect. Closing this.
